# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedurl',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Url'),
        ),
    ]
