# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170413_0536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
        migrations.RemoveField(
            model_name='savedurl',
            name='labels',
        ),
        migrations.AddField(
            model_name='savedurl',
            name='label',
            field=models.ManyToManyField(to='main.Label'),
        ),
    ]
