# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170413_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedurl',
            name='citation',
        ),
        migrations.AddField(
            model_name='citation',
            name='url',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citation',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
    ]
