# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170413_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Label')),
            ],
        ),
        migrations.RemoveField(
            model_name='citation',
            name='url',
        ),
        migrations.RemoveField(
            model_name='citation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedurl',
            name='label',
        ),
        migrations.AddField(
            model_name='citation',
            name='saved_url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.SavedUrl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urllabel',
            name='saved_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SavedUrl'),
        ),
    ]
