# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170414_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedurl',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedurl',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Url'),
        ),
        migrations.AlterField(
            model_name='savedurl',
            name='url_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='savedurl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
