# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170415_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedurl',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Url'),
        ),
        migrations.AlterField(
            model_name='savedurl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
