# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170416_0949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedurl',
            unique_together=set([]),
        ),
    ]
