# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170416_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urllabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='urllabel',
            name='saved_url',
        ),
        migrations.AddField(
            model_name='label',
            name='saved_url',
            field=models.ManyToManyField(to='main.SavedUrl'),
        ),
        migrations.DeleteModel(
            name='UrlLabel',
        ),
    ]
